// <auto-generated />
namespace LiberLend.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddReservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReservation));
        
        string IMigrationMetadata.Id
        {
            get { return "202107050026017_AddReservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
